default:
  image: docker:latest
  services:
    - docker:dind
  cache:
    paths:
      - .m2/repository

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  TAG: hello:v0.1

stages:
  - package
  - deploy

maven-package:
  image: maven:3.5-jdk-8-alpine
  tags:
    - maven
  stage: package
  script:
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar   #此处添加缓存

build-master:
  tags:
    - docker
  stage: deploy
  script:
    - docker build -t $TAG .
    - docker rm -f test || true
    - docker run -d --name test -p 8080:8080 $TAG
  only:
    - master
