concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "maven-java"
  url = "http://192.168.239.3:8929/"
  token = "s8q3H4SVtNejMjWWhysn"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "maven:3.5-jdk-8-alpine"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/home/docker/gitlab/.m2:/root/.m2", "/home/docker/gitlab-runner/maven/settings.xml:/usr/share/maven/conf/settings.xml"]
    shm_size = 0

[[runners]]
  name = "shell"
  url = "http://192.168.239.3:8929/"
  token = "GfD98WQQZddpxKyTvy31"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "docker-run"
  url = "http://192.168.239.3:8929/"
  token = "45QtuYF1qf45rzKmpC81"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    pull_policy = "if-not-present"
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/usr/bin/docker:/usr/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
    environment = ["DOCKER_TLS_CERTDIR="]
